version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: chattingo-mysql
    restart: always
    env_file:
      - ./backend/.env
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 30s

  backend:
    build: ./backend
    container_name: chattingo-backend
    restart: always
    env_file:
      - ./backend/.env
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    container_name: chattingo-frontend
    restart: always
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    ports:
      - "3000:3000"
    command: ["npm", "start"]
    volumes:
      - ./frontend:/usr/src/app

volumes:
  mysql_data:
